### ISSUE TITLE
Cannot compile locally

### ISSUE THREAD

**Issue by ThePrimeDev** [CivMC/RandomSpawn#8]
![image](https://user-images.githubusercontent.com/81071854/196345304-7a4a8b7f-38bc-4e8a-8735-8d3386c98f47.png)
Hello. I tried to compile the plugin locally, on Linux, and Windows also, i set the System Environment Variables GITHUB_ACTOR to my username and GITHUB_TOKEN to my pass, but it doesnt seem to work. Also, if I access https://maven.pkg.github.com/CivMC/CivGradle gives me a 404 not found error. Your help is appreciated, thank you!

**Comment by Diet-Cola** [comment]
Hi there,

Please use the branch here: https://github.com/CivMC/RandomSpawn/tree/civgradle-2

You can compile using `gradle reobf` however does still use the environment variables. 

Just to double check, your `GITHUB_TOKEN` env variable shouldn't be your password, it should be a PAT token found here: https://github.com/settings/tokens

**Comment by Diet-Cola** [comment]
Did `gradle reobf` run without build failed? 

build won't compile a spigot obfuscated jar if I remember rightly

**Comment by ThePrimeDev** [comment]
> Did `gradle reobf` run without build failed?
> 
> build won't compile a spigot obfuscated jar if I remember rightly

@Diet-Cola No, it gave me Build Failed. As shown in pic. Also, I just need a jar which works on paper, I dont strictly need it to be obfed

**Comment by ThePrimeDev** [comment]
Update: On Win I'm getting somewhere

![image](https://user-images.githubusercontent.com/81071854/196623667-2e7f8e31-3c9f-4db6-ad2c-eadcc24c9202.png)

**Comment by ThePrimeDev** [comment]
@Diet-Cola 
![image](https://user-images.githubusercontent.com/81071854/197245381-273143c8-dd69-4294-8232-50afcddd4ac0.png)
Still this problem, after 2 days of struggling

**Comment by Diet-Cola** [comment]
Cc @AngrySoundTech 

I've never encountered that error so I'm not sure what's going wrong, only thing I can think to suggest is maybe `gradlew reobf` however I'm out of ideas

**Comment by Diet-Cola** [comment]
From SoundTech while hes away: 
certificate error, probably the wrong version of Java or bad system time

Could you verify both these things? @ThePrimeDev
